version: '3.8'
services:
  db:
    image: postgres:15
    container_name: task_managment_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sara_postgres
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
